# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1vOOEog_1dHFfrlW68iiCq-Dn8EviyTwU
"""

#creating a whole model using logistic regression
import numpy as np;
import pandas as pd;
import seaborn as sns;
import matplotlib.pyplot as plt;
import warnings
warnings.filterwarnings('ignore')

df = sns.load_dataset("titanic")

df.head()

df.columns

df.info()

df.drop(['class', 'who', 'adult_male', 'deck', 'embark_town',
       'alive', ],axis=1,inplace=True)

df.info()

#filling all null values of age with the mean
df["age"].fillna(df["age"].mean(), inplace = True)

#droped all the rows to make equals to no. of embarked rows
df.dropna(subset=["embarked"],inplace=True)

df.info()

#label encoding
from sklearn.preprocessing import LabelEncoder
le= LabelEncoder()

df.head()

df['sex']=le.fit_transform(df['sex']);
df['embarked']=le.fit_transform(df['embarked']);# s=2,c=0, Q=1

df.head()

df.astype(int)#to make the values of true fals in 0s and 1s

# deividing in x and y labels (x me sab kuch hai accept survived as we droped it )
# and y me sirf survived is there
x= df.drop("survived",axis=1)
y=df["survived"]

# doing train and split test
from sklearn.model_selection import train_test_split

X_train, X_test, Y_train, Y_test = train_test_split(x,y,test_size=0.2,random_state=42)

#Feature engineering
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.fit_transform(X_test) # till here did standard scalling

# Now implementiung KNN
from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors=5)
# training model for knn
knn_model.fit(X_train_scaled,Y_train)

#now see predictions
y_pred_knn=knn_model.predict(X_test_scaled)

#using confusion matrix and f1 score , accuracy , f1_score ,etc
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

#accuracy of model
accuracy_score(Y_test, y_pred_knn)

#consfusion matrix for the model
confusion_matrix(Y_test, y_pred_knn)

#now will see the classifictaion report where we will going tom see each and everything like precesion , f1_score, etc
classification_report(Y_test, y_pred_knn)

#another way for cleaner version
print(classification_report(Y_test, y_pred_knn))

