# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hwzqDgwm41w-3NZf9t1dE14IA9gru8Nu
"""

#Dimensity Reduction

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs #make_blobs is used for importing datasets
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

X,y = make_blobs(n_samples=500,n_features=5,centers=3,cluster_std=1.5,random_state=42)

X

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_scaled

#use case of (Principle Component Analysis)
pca = PCA(n_components=2) # converted 5 features into 2 features
X_pca = pca.fit_transform(X_scaled)

X_pca

df_pca = pd.DataFrame(X_pca,columns=['PC1','PC2']) # pc1 and pc2 are lines
df_pca['label']=y

sns.scatterplot(data=df_pca,x='PC1',y='PC2',hue='label')#using this pc1 and pc2 we have reduced the dimensity

#This is all about dimensity reduction