# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17ivqnigUu7duiIProYUqtoMJTfLHtFtv
"""

#unsupervised learning
#implementation of k means clustering

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import make_blobs # this helps to generate the datasets or clsuters
# it doesnt make clusters but generates dat for clusters
from sklearn.cluster import KMeans
from sklearn.preprocessing import StandardScaler

X, y_true = make_blobs(n_samples=500, centers =3, cluster_std=0.60,random_state=42)

X

df=pd.DataFrame(X, columns=['Feature1','Feature2']) #converted X values in column wise properly like feature1 and feature2

df

scaler = StandardScaler()
X_scaled = scaler.fit_transform(df)

# now will see the use of Elbow Method
#for to know that how many values of k are required to make clusters
#Now to use the elbow method first we have to find the values of WCSS
# and how we will capture those values and we call WCSS as inertia

inertia=[]
k_range = range(1,11)

#lets do k means clustering
for k in k_range:
  kmeans=KMeans(n_clusters=k,random_state=42)
  kmeans.fit(X_scaled)
  inertia.append(kmeans.inertia_)

inertia

plt.plot(k_range, inertia, marker='o') # graph visualization using matplotlib
# this is the lebow curve

kmeans_final= KMeans(n_clusters=3, random_state=42) # final clusters are 3
#as we saw in graph after 3rd point it is same

cluster_labels=kmeans_final.fit_predict(X_scaled) # findng the labels of clusters

cluster_labels

df['cluster']=cluster_labels

sns.scatterplot(x=df['Feature1'],
                y=df['Feature2'],
                hue=df['cluster'],
                palette='viridis'
                ) # this is the scatter plot and these are 3 clusters

#This is all about k means clustering

#DB SCAN ALGO IMPLEMENTEATION
#->will also see the diff between k_MEANS and DBSCAN

# k-means
from sklearn.datasets import make_moons

X,y_true=make_moons(n_samples=500, noise=0.05, random_state=42)

from sklearn.cluster import KMeans,DBSCAN

df=pd.DataFrame(X, columns=['Feature1','Feature2'])

scaler=StandardScaler()
X_scaled=scaler.fit_transform(df)

kmeans=KMeans(n_clusters=2, random_state=42)
kmeans_labels=kmeans.fit_predict(X_scaled)

df['kmeans_cluster']=kmeans_labels

sns.scatterplot(x=df['Feature1'],
                y=df['Feature2'],
                hue=df['kmeans_cluster'],
                palette='tab10'
                )
#

# dbScan
dbscan=DBSCAN(eps=0.2, min_samples=5)
dbscan_labels=dbscan.fit_predict(X_scaled)

df['dbscan_cluster']=dbscan_labels

sns.scatterplot(x=df['Feature1'],
                y=df['Feature2'],
                hue=df['dbscan_cluster'],
                palette='tab10'
                )

# this is all about and u can see the diff clearly in both the graphs