# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iPzk3emLNzBvWrHL9k5OcGfjJgb2tK1z
"""

#implementing anesemble learning
#first one is stacking

from sklearn.model_selection import train_test_split
from sklearn.ensemble import StackingClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, classification_report
import seaborn as sns

df=sns.load_dataset('iris')

df.head()

X=df.drop('species',axis=1)
y=df['species']

X_train, X_test, y_train, y_test = train_test_split(
...     X, y, test_size=0.33, random_state=42)

# base models in stacking
base_learners=[
    ('dt',DecisionTreeClassifier(random_state=42)),
    ('svc',SVC(probability=True,kernel='rbf',random_state=42)),
    ('lr',LogisticRegression(max_iter=1000))
]

#meta models in stacking
meta_learner=LogisticRegression(max_iter=1000)

#creating stacking
stacking_clf=StackingClassifier(
    estimators=base_learners,
    final_estimator=meta_learner,
    cv=5
)

stacking_clf.fit(X_train,y_train)

y_pred=stacking_clf.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)

accuracy

# now using bagging(Random Forest Search)
from sklearn.ensemble import RandomForestClassifier

rf_model=RandomForestClassifier(
    n_estimators=100,# no of trees
    max_depth=None,#let trees grow fullly
    random_state=42
)

rf_model.fit(X_train,y_train)

pred = rf_model.predict(X_test)

acc = accuracy_score(y_test,pred)

acc

#now will going to implement boosting
# ada bossting
# gradient bossting
# XG boosting

from sklearn.ensemble import AdaBoostClassifier, GradientBoostingClassifier

from xgboost import XGBClassifier

# implementing ada bossting
ada_model = AdaBoostClassifier(n_estimators=100, random_state=42)

ada_model.fit(X_train,y_train)

y_pred = ada_model.predict(X_test)

accuracy = accuracy_score(y_test,y_pred)

accuracy

#implementing gradient boosting
gb_model = GradientBoostingClassifier(n_estimators=100, learning_rate=0.1, random_state=42)

gb_model.fit(X_train,y_train)

y_pred=gb_model.predict(X_test)

accuracy = accuracy_score(y_pred,y_test)

accuracy

#implememting XG bossting
xgb_model= XGBClassifier(n_estimators =100,learning_rate=0.1,max_depth=3, use_label_encoder=True,eval_metric='mlogloss', random_state=42)

# here we did label encoding beacuse model is expecting numeric labels, but you are giving it string labels.
#Expected: [0 1 2]
#Got: ['setosa' 'versicolor' 'virginica']
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

y_train_encoded = le.fit_transform(y_train)
y_test_encoded = le.transform(y_test)

xgb_model.fit(X_train,y_train_encoded)

y_pred=xgb_model.predict(X_test)

accuracy=accuracy_score(y_test_encoded,y_pred)

accuracy

