# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sqxod5G_ZV90YpnkTMRk0zD178FMU7ms
"""

# this project is all about how the predictions are going to change when you change the hyperparamets

import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

df = sns.load_dataset('iris')

df.head()

df['species'].unique()

# we are not preprocessing and cleaning the data as it is already done
#the file is already preprocessed and cleaned in seaborn
from sklearn.model_selection import train_test_split

X=df.drop('species',axis=1)
Y=df['species']

X

# when we do cross validation we dont need to do train test split
#and still iam not using cross validation so doing train test split

X_train, X_test, y_train, y_test = train_test_split(
                X, Y, test_size=0.33, random_state=42)

# for creating model we have to train the training data and testing helps in prediction
# using diff algo to see how paramenters affects

from sklearn.neighbors import KNeighborsClassifier

model_knn= KNeighborsClassifier(n_neighbors=13)

model_knn.fit(X_train,y_train)

model_knn.score(X_test,y_test)

# now using diff algo
from sklearn.svm import SVC

model_svm = SVC(gamma="auto")

model_svm.fit(X_train,y_train)

model_svm.score(X_test,y_test)

# here we have changed the hyperparameters so many times for both algos and checked the different scores

#now we will find the best hyperparameters using Grid Search CV
from sklearn.model_selection import GridSearchCV

classifier = GridSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel' : ['rbf','linear'],
},cv=5,return_train_score=False)

classifier.fit(X,Y)# here we dont need to do train test split beacuse it is not usied in cross validation
# thats why directly using x and y

classifier.cv_results_

results = pd.DataFrame(classifier.cv_results_)

results

results[['param_C',	'param_kernel', 'mean_test_score']]

#this is our final results and got to know that these are the best hyperparemeters for C , kernel and gamma

#now applying Random Searc CV
from sklearn.model_selection import RandomizedSearchCV

classifier_r = RandomizedSearchCV((model_svm),{
    'C': [1,10,20,30],
    'kernel' : ['rbf','linear'],
},n_iter=4,cv=5,return_train_score=False)

classifier_r.fit(X,Y)

classifier_r.cv_results_

resultss = pd.DataFrame(classifier_r.cv_results_)

resultss

resultss[['param_C',	'param_kernel', 'mean_test_score']]

#this is the implementation of Random Search CV